name: varchas_dream_11
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  font_awesome_flutter: ^10.1.0
  http: ^0.13.4
  intl: ^0.17.0
  flutter_profile_picture: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/college_logos/
    - images/sports_logos/
    - jsonfile/

  fonts:
    - family: OpenSans Light
      fonts:
        - asset: fonts/OpenSans-Light.ttf

    - family: OpenSans Regular
      fonts:
        - asset: fonts/OpenSans-Regular.ttf

    - family: OpenSans Medium
      fonts:
        - asset: fonts/OpenSans-Medium.ttf

    - family: OpenSans Bold
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
